Hola bandarres



sembla que fent les tasques següents han ocorregut el següents errors:

{# for task_result in task_results  #}
    {{ task_result.task_name }}
    {{ task_result.task_error }}
{# endfor #}


Podeu tornar a intentar-ho fent click aqui: {{ task_url }}

Em sap greu (｡•́︿•̀｡)

Salutacions,
Your lovely SomExchanger99 <3

